### ISSUE TITLE
Flip Privacy & Ownership URLs on Standard page

### ISSUE THREAD

**Issue by ginnyfahs** [TheDigitalStandard/thedigitalstandard.org#18]
When viewing the Standard from [this page](https://polite-moon.cloudvent.net/standard/) the Privacy button takes me to an [ownership URL](https://polite-moon.cloudvent.net/standard/ownership/) and the ownership button to the [privacy URL](https://polite-moon.cloudvent.net/standard/privacy/). We should flip flop these two so that buttons link to associated tests.

**Comment by stephtngu-CR** [comment]
cc: @tbeck

**Comment by tbeck** [comment]
This should be fixed as part of this PR: #19

**Comment by tbeck** [comment]
@benrito - would you like me to close issues or reassign them for review?

**Comment by ginnyfahs** [comment]
Is this fixed? In a website demo yesterday, we were still having the same issue when navigating from this page https://polite-moon.cloudvent.net/standard/

**Comment by tbeck** [comment]
@ginnyfahs - I apologize. I misunderstood, and thought this was a reference to the navigation [here](https://gyazo.com/203b3561307b43d0e571706e15b81e78) which was also flipped. We have pushed another fix for the standard page. https://polite-moon.cloudvent.net/standard/

Can you test and if fixed, close this issue?

Thanks!

**Comment by ginnyfahs** [comment]
Thanks for addressing this so quickly @tbeck ! The hrefs are correct now.

But I noticed that both https://polite-moon.cloudvent.net/standard/ownership/ and https://polite-moon.cloudvent.net/standard/privacy/ flash a quick "Uh Oh" message before the redirect. It happens too quickly for me to snap a screenshot, but blinks consistently every time. Can we look into it?

Happy to open a new issue, as well, if easier -- just let me know

**Comment by benrito** [comment]
@ginnyfahs I think we addressed in #23 but if you're still seeing, we may want to reopen. Thank you for flagging!

**Comment by ginnyfahs** [comment]
Sounds good! I'll pickup with this on #23
